/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/astronauta.gltf')
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    // Reset and fade in animation after an index has been changed
    actions[names].reset().fadeIn(0.5).play()
    // In the clean-up phase, fade it out
    return () => actions[names].fadeOut(0.5)
  }, [ actions, names])
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.lipstick_lips.geometry}
        material={nodes.lipstick_lips.material}
        position={[-0.36, 2.14, 0.57]}
        rotation={[-1.2, -0.1, -1.16]}
      />
      <mesh
        geometry={nodes.lipstick_lips001.geometry}
        material={nodes.lipstick_lips001.material}
        position={[0.8, 1.1, 1]}
        rotation={[0.34, 0.09, 2.95]}
      />
      <mesh
        geometry={nodes.lipstick_lips002.geometry}
        material={nodes.lipstick_lips002.material}
        position={[1.36, 2.18, -0.23]}
        rotation={[-1.49, 0.13, 1.96]}
      />
      <mesh
        geometry={nodes.lipstick_lips003.geometry}
        material={nodes.lipstick_lips003.material}
        position={[0.56, 1.61, -1.48]}
        rotation={[-2.74, 0.14, -1.72]}
      />
      <group name="Object_9" position={[-2.13, 1.66, 1.34]} rotation={[-0.08, -0.47, -0.05]} scale={[0, 0, 0]}>
        <mesh geometry={nodes.Sphere004_character_mtl_0.geometry} material={materials.character_mtl} />
        <mesh geometry={nodes.Sphere004_character_mtl_0_1.geometry} material={materials.rocket_mtl} />
        <mesh geometry={nodes.Sphere004_character_mtl_0_2.geometry} material={materials.fire_mtl} />
      </group>
      <mesh
        geometry={nodes.Icosphere.geometry}
        material={materials['Material.001']}
        position={[0.39, 1.26, -0.23]}
        scale={1.45}
      />
    </group>
  )
}

useGLTF.preload('/astronauta.gltf')
