/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/fin.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[2.06, 0.64, 0.53]} rotation={[-1.86, -0.81, 1.74]} scale={0.08}>
        <mesh geometry={nodes['������_0'].geometry} material={nodes['������_0'].material} />
        <group rotation={[0, 0, Math.PI / 2]}>
          <mesh geometry={nodes['������001_0'].geometry} material={nodes['������001_0'].material} />
        </group>
        <group position={[0, 0, 0.08]} rotation={[0.82, 0.63, -2.64]} scale={[0.77, 0.04, 0.77]}>
          <mesh geometry={nodes['������002_0'].geometry} material={nodes['������002_0'].material} />
        </group>
        <group rotation={[0, 0, -Math.PI]}>
          <mesh geometry={nodes['������003_0'].geometry} material={nodes['������003_0'].material} />
        </group>
        <group rotation={[0, 0, -Math.PI / 2]}>
          <mesh geometry={nodes['������004_0'].geometry} material={nodes['������004_0'].material} />
        </group>
        <group position={[0, 0, 0.08]} rotation={[0.82, 0.63, -2.64]} scale={[0.77, 0.04, 0.77]}>
          <mesh geometry={nodes['������005_0'].geometry} material={nodes['������005_0'].material} />
        </group>
        <group position={[0, 0, 0.08]} rotation={[-0.82, 0.63, -0.5]} scale={[0.77, 0.04, 0.77]}>
          <mesh geometry={nodes['������006_0'].geometry} material={nodes['������006_0'].material} />
        </group>
        <group position={[0, 0, 0.08]} rotation={[-0.82, -0.63, 0.5]} scale={[0.77, 0.04, 0.77]}>
          <mesh geometry={nodes['������007_0'].geometry} material={nodes['������007_0'].material} />
        </group>
        <group position={[0, 0, 0.08]} rotation={[0.82, -0.63, 2.64]} scale={[0.77, 0.04, 0.77]}>
          <mesh geometry={nodes['������008_0'].geometry} material={nodes['������008_0'].material} />
        </group>
        <group position={[0, 0, -0.03]} rotation={[-0.12, 0.03, 2.88]} scale={[0.01, 0.01, 0.12]}>
          <mesh geometry={nodes['������009_0'].geometry} material={nodes['������009_0'].material} />
        </group>
        <group position={[0, 0, -1.04]} rotation={[-2.59, 0.18, 0.28]} scale={[0.77, 0.04, 0.77]}>
          <mesh geometry={nodes['������010_0'].geometry} material={nodes['������010_0'].material} />
        </group>
        <group position={[0, 0, -1.04]} rotation={[-2.59, -0.17, -0.27]} scale={[0.77, 0.04, 0.77]}>
          <mesh geometry={nodes['������011_0'].geometry} material={nodes['������011_0'].material} />
        </group>
        <group position={[0, 0, -1.04]} rotation={[2.94, -0.55, -1.95]} scale={[0.77, 0.04, 0.77]}>
          <mesh geometry={nodes['������012_0'].geometry} material={nodes['������012_0'].material} />
        </group>
        <group position={[0, 0, -1.04]} rotation={[-2.93, -0.54, -1.18]} scale={[0.77, 0.04, 0.77]}>
          <mesh geometry={nodes['������013_0'].geometry} material={nodes['������013_0'].material} />
        </group>
        <group position={[0, 0, -1.04]} rotation={[2.59, -0.18, -2.86]} scale={[0.77, 0.04, 0.77]}>
          <mesh geometry={nodes['������014_0'].geometry} material={nodes['������014_0'].material} />
        </group>
        <group position={[0, 0, -1.04]} rotation={[2.59, 0.17, 2.87]} scale={[0.77, 0.04, 0.77]}>
          <mesh geometry={nodes['������015_0'].geometry} material={nodes['������015_0'].material} />
        </group>
        <group position={[0, 0, -1.04]} rotation={[-2.94, 0.55, 1.19]} scale={[0.77, 0.04, 0.77]}>
          <mesh geometry={nodes['������016_0'].geometry} material={nodes['������016_0'].material} />
        </group>
        <group position={[0, 0, -1.04]} rotation={[2.93, 0.54, 1.96]} scale={[0.77, 0.04, 0.77]}>
          <mesh geometry={nodes['������017_0'].geometry} material={nodes['������017_0'].material} />
        </group>
        <group rotation={[-Math.PI / 2, Math.PI / 4, Math.PI / 2]} scale={[0.38, 0.25, 0.25]}>
          <mesh geometry={nodes['������018_0'].geometry} material={nodes['������018_0'].material} />
        </group>
        <group rotation={[-Math.PI / 2, -Math.PI / 4, Math.PI / 2]} scale={[0.38, 0.25, 0.25]}>
          <mesh geometry={nodes['������019_0'].geometry} material={nodes['������019_0'].material} />
        </group>
        <group rotation={[Math.PI / 2, -Math.PI / 4, -Math.PI / 2]} scale={[0.38, 0.25, 0.25]}>
          <mesh geometry={nodes['������020_0'].geometry} material={nodes['������020_0'].material} />
        </group>
        <group rotation={[Math.PI / 2, Math.PI / 4, -Math.PI / 2]} scale={[0.38, 0.25, 0.25]}>
          <mesh geometry={nodes['������021_0'].geometry} material={nodes['������021_0'].material} />
        </group>
        <group position={[0, 0, 0.49]} scale={[1, 1, 0.21]}>
          <mesh geometry={nodes['��������������_0'].geometry} material={nodes['��������������_0'].material} />
        </group>
        <group position={[0, 0, 1.25]} scale={[0.79, 0.79, 0.45]}>
          <mesh geometry={nodes['��������������001_0'].geometry} material={nodes['��������������001_0'].material} />
        </group>
        <group position={[0, 0, 1.11]} scale={[0.76, 0.76, 0.43]}>
          <mesh geometry={nodes['��������������002_0'].geometry} material={nodes['��������������002_0'].material} />
        </group>
        <group position={[0.89, -0.27, 0.71]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.04}>
          <mesh geometry={nodes['��������������003_0'].geometry} material={nodes['��������������003_0'].material} />
        </group>
        <group position={[0, 0, 0.07]} scale={[0.27, 0.27, 0.29]}>
          <mesh geometry={nodes['��������������004_0'].geometry} material={nodes['��������������004_0'].material} />
        </group>
        <mesh geometry={nodes['��������������005_0'].geometry} material={nodes['��������������005_0'].material} />
        <mesh geometry={nodes['��������������006_0'].geometry} material={nodes['��������������006_0'].material} />
        <group position={[-0.01, 0, 0.35]} rotation={[0, 0, 2.36]} scale={0.7}>
          <mesh geometry={nodes['������������������_0'].geometry} material={nodes['������������������_0'].material} />
        </group>
        <group position={[-0.01, 0, 0.35]} rotation={[0, 0, -2.36]} scale={0.7}>
          <mesh geometry={nodes['������������������001_0'].geometry} material={nodes['������������������001_0'].material} />
        </group>
        <group position={[-0.01, 0, 1.42]} scale={[1, 0.06, 1]}>
          <mesh geometry={nodes['������������������005_0'].geometry} material={nodes['������������������005_0'].material} />
        </group>
        <group position={[0, 0, 1.43]} scale={0.99}>
          <mesh geometry={nodes['��������������������_0'].geometry} material={nodes['��������������������_0'].material} />
        </group>
      </group>
      <mesh geometry={nodes.Icosphere.geometry} material={materials['Material.002']} position={[0.01, 0.2, -0.17]} rotation={[-0.32, 0.03, -0.13]} />
      <mesh geometry={nodes.Icosphere001.geometry} material={materials['Material.001']} position={[0.01, 0.2, -0.17]} rotation={[-0.24, 0.03, -0.13]} />
      <mesh geometry={nodes.Icosphere056.geometry} material={materials['Material.010']} position={[1.47, -0.42, 2.55]} scale={[0.08, 0.05, 0.11]} />
      <mesh geometry={nodes.USMC_flagobj001.geometry} material={materials['wire_088144225.001']} position={[0, 1.24, -0.12]} rotation={[Math.PI / 2, -0.01, -0.42]} scale={0.01} />
      <group position={[-1028.96, 871.68, 2301.68]} rotation={[2.92, 0.77, 0.23]} scale={0.72}>
        <mesh geometry={nodes.Mesh418.geometry} material={materials.patina} />
        <mesh geometry={nodes.Mesh418_1.geometry} material={materials.black} />
        <mesh geometry={nodes.Mesh418_2.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Mesh418_3.geometry} material={materials.white} />
        <mesh geometry={nodes.Mesh418_4.geometry} material={materials.grey} />
        <mesh geometry={nodes.Mesh418_5.geometry} material={materials.cargodoors} />
        <mesh geometry={nodes.Mesh418_6.geometry} material={materials.USFLAGBLUE} />
        <mesh geometry={nodes.Mesh418_7.geometry} material={materials.USFLAGRED} />
        <mesh geometry={nodes.Mesh418_8.geometry} material={materials.USFLAGWHITE} />
        <mesh geometry={nodes.Mesh418_9.geometry} material={materials.glass} />
        <mesh geometry={nodes.Mesh418_10.geometry} material={materials.red} />
        <mesh geometry={nodes.Mesh418_11.geometry} material={materials.bluebg} />
      </group>
      <mesh geometry={nodes.eth_logo.geometry} material={nodes.eth_logo.material} position={[-1.66, -0.13, 2.42]} rotation={[2.77, -0.36, 0.14]} scale={0.03} />
      <mesh geometry={nodes.eth_logo001.geometry} material={nodes.eth_logo001.material} position={[-0.39, 0.01, 2.83]} rotation={[3.13, 0, 0]} scale={0.02} />
      <mesh geometry={nodes.eth_logo002.geometry} material={nodes.eth_logo002.material} position={[3.57, -0.04, -0.26]} rotation={[-2.69, 0, -0.17]} scale={0.03} />
      <mesh geometry={nodes.eth_logo003.geometry} material={nodes.eth_logo003.material} position={[2.35, -0.04, -2.76]} rotation={[2.86, 0, -0.24]} scale={0.02} />
      <mesh geometry={nodes.eth_logo004.geometry} material={nodes.eth_logo004.material} position={[-0.52, -0.16, -3.1]} rotation={[3.13, -0.01, 0.81]} scale={0.02} />
      <mesh geometry={nodes.eth_logo005.geometry} material={nodes.eth_logo005.material} position={[-2.69, -0.38, -0.56]} rotation={[2.27, 0.6, 0.15]} scale={0.02} />
      <mesh geometry={nodes.eth_logo006.geometry} material={nodes.eth_logo006.material} position={[1.23, -0.12, 2.81]} rotation={[-3.14, -0.01, 1.95]} scale={0.02} />
      <group position={[-1014.36, 922.18, 2296.6]} rotation={[2.92, 0.77, 0.23]} scale={0.72}>
        <mesh geometry={nodes.Mesh005.geometry} material={materials['patina.002']} />
        <mesh geometry={nodes.Mesh005_1.geometry} material={materials['black.002']} />
        <mesh geometry={nodes.Mesh005_2.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Mesh005_3.geometry} material={materials['white.002']} />
        <mesh geometry={nodes.Mesh005_4.geometry} material={materials['grey.002']} />
        <mesh geometry={nodes.Mesh005_5.geometry} material={materials['cargodoors.002']} />
        <mesh geometry={nodes.Mesh005_6.geometry} material={materials['USFLAGBLUE.002']} />
        <mesh geometry={nodes.Mesh005_7.geometry} material={materials['USFLAGRED.002']} />
        <mesh geometry={nodes.Mesh005_8.geometry} material={materials['USFLAGWHITE.002']} />
        <mesh geometry={nodes.Mesh005_9.geometry} material={materials['glass.002']} />
        <mesh geometry={nodes.Mesh005_10.geometry} material={materials['red.002']} />
        <mesh geometry={nodes.Mesh005_11.geometry} material={materials['bluebg.002']} />
      </group>
      <mesh geometry={nodes.Cylinder1.geometry} material={nodes.Cylinder1.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <mesh geometry={nodes.WheelCarcas.geometry} material={nodes.WheelCarcas.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <mesh geometry={nodes.Wheel.geometry} material={nodes.Wheel.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <mesh geometry={nodes.Cylinder1_1.geometry} material={nodes.Cylinder1_1.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <mesh geometry={nodes.WheelCarcas_1.geometry} material={nodes.WheelCarcas_1.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <mesh geometry={nodes.Wheel_1.geometry} material={nodes.Wheel_1.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <mesh geometry={nodes.Cylinder1_2.geometry} material={nodes.Cylinder1_2.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <mesh geometry={nodes.WheelCarcas_2.geometry} material={nodes.WheelCarcas_2.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <mesh geometry={nodes.Wheel_2.geometry} material={nodes.Wheel_2.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <mesh geometry={nodes.Cone.geometry} material={nodes.Cone.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <mesh geometry={nodes.Cone1.geometry} material={nodes.Cone1.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <mesh geometry={nodes.Cube2.geometry} material={nodes.Cube2.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <mesh geometry={nodes.Cube1.geometry} material={nodes.Cube1.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <mesh geometry={nodes.Cube2_1.geometry} material={nodes.Cube2_1.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <mesh geometry={nodes.Cube1_1.geometry} material={nodes.Cube1_1.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <mesh geometry={nodes.Cube_1.geometry} material={nodes.Cube_1.material} position={[-0.63, 0.87, 0.66]} rotation={[2.79, 0.55, 1.81]} scale={0} />
      <group position={[-0.6, 0.85, 0.62]} rotation={[2.79, 0.55, 1.81]} scale={0}>
        <mesh geometry={nodes.Cube_2_1.geometry} material={nodes.Cube_2_1.material} />
        <mesh geometry={nodes.Cube_2_2.geometry} material={nodes.Cube_2_2.material} />
      </group>
      <group position={[0.77, -0.09, -1.1]} rotation={[-0.08, -0.49, -1.36]} scale={0}>
        <mesh geometry={nodes.Cube_2002.geometry} material={nodes.Cube_2002.material} />
        <mesh geometry={nodes.Cube_2002_1.geometry} material={nodes.Cube_2002_1.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/fin.glb')
