/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/globe2.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Icosphere.geometry} material={materials['Material.002']} position={[-0.09, 1.21, -0.17]} />
      <mesh
        geometry={nodes.Icosphere001.geometry}
        material={materials['Material.001']}
        position={[-0.09, 1.21, -0.17]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[0.47, 1.96, -0.53]}
        rotation={[-0.34, -0.18, -0.64]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[0.51, 1.99, -0.43]}
        rotation={[-0.34, -0.17, -0.65]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={nodes.Plane003.material}
        position={[0.52, 1.92, -0.48]}
        rotation={[-0.34, -0.18, -0.64]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[0.39, 2, -0.57]}
        rotation={[-0.34, -0.18, -0.64]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={nodes.Plane005.material}
        position={[0.44, 2.04, -0.48]}
        rotation={[-0.34, -0.17, -0.66]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={nodes.Plane006.material}
        position={[0.61, 1.93, -0.06]}
        rotation={[-0.35, -0.17, -0.67]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={nodes.Plane007.material}
        position={[0.58, 1.91, 0.04]}
        rotation={[-0.35, -0.16, -0.67]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={nodes.Plane008.material}
        position={[0.65, 1.88, -0.04]}
        rotation={[-0.34, -0.17, -0.66]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        geometry={nodes.Plane009.geometry}
        material={nodes.Plane009.material}
        position={[0.93, 1.26, -0.09]}
        rotation={[-1.03, 0.04, -1.27]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        geometry={nodes.Plane010.geometry}
        material={nodes.Plane010.material}
        position={[0.93, 1.17, -0.06]}
        rotation={[-1.03, 0.04, -1.27]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        geometry={nodes.Plane011.geometry}
        material={nodes.Plane011.material}
        position={[0.91, 1.19, -0.18]}
        rotation={[-1.03, 0.04, -1.27]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        geometry={nodes.Plane012.geometry}
        material={nodes.Plane012.material}
        position={[-0.42, 1.52, 0.75]}
        rotation={[1.25, 0.06, 0.58]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        geometry={nodes.Plane013.geometry}
        material={nodes.Plane013.material}
        position={[-0.35, 1.59, 0.75]}
        rotation={[1.25, 0.06, 0.58]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        geometry={nodes.Plane014.geometry}
        material={nodes.Plane014.material}
        position={[-0.44, 1.59, 0.7]}
        rotation={[1.25, 0.06, 0.58]}
        scale={[0.03, 0.03, 0.03]}
      />
      <mesh
        geometry={nodes.Plane016.geometry}
        material={nodes.Plane016.material}
        position={[0.88, 1.62, 0.27]}
        rotation={[0, -0.31, -0.2]}
        scale={[-0.04, -0.03, 0.04]}
      />
      <mesh
        geometry={nodes.Plane015.geometry}
        material={nodes.Plane015.material}
        position={[0.91, 1.54, 0.28]}
        rotation={[0, -0.31, -0.2]}
        scale={[-0.04, -0.03, 0.04]}
      />
      <mesh
        geometry={nodes.Plane017.geometry}
        material={nodes.Plane017.material}
        position={[-0.13, 1.62, 0.93]}
        rotation={[0.06, -1.4, -0.2]}
        scale={[-0.04, -0.03, 0.04]}
      />
      <mesh
        geometry={nodes.Plane018.geometry}
        material={nodes.Plane018.material}
        position={[0.12, 2.2, 0.04]}
        rotation={[0, 0, -0.17]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane019.geometry}
        material={nodes.Plane019.material}
        position={[0.28, 0.87, 0.72]}
        rotation={[1.87, 0, -0.17]}
        scale={0.01}
      />
    </group>
  )
}

useGLTF.preload('/globe2.gltf')
