/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/test.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Object_17" position={[-0.2, 0.19, -0.35]} scale={0}>
        <mesh geometry={nodes.Plane007_fire_mtl_0.geometry} material={materials['fire_mtl.001']} />
        <mesh geometry={nodes.Plane007_fire_mtl_0_1.geometry} material={materials['rocket_mtl.001']} />
        <mesh geometry={nodes.Plane007_fire_mtl_0_2.geometry} material={materials['character_mtl.001']} />
        <mesh geometry={nodes.Plane007_fire_mtl_0_3.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane007_fire_mtl_0_4.geometry} material={materials['lips.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/test.gltf')
